### ISSUE TITLE
Native compilation with GraalVM

### ISSUE THREAD

**Issue by jponge** [vertx-howtos/vertx-howtos.github.io#7]
How to compile Vert.x applications to native code with GraalVM / SubstrateVM. This would also include the methodology to spot necessary code substitutions and reflective accesses surgery to get working native executables.

**Comment by jponge** [comment]
@pmlopes still interested? 😉

**Comment by pmlopes** [comment]
It's on my todo list

**Comment by jponge** [comment]
Implemented

**Comment by pmlopes** [comment]
fixed!
